### PR TITLE
Add Eurus mainnet and testnet contract addresses and initial block 

### PR DESCRIPTION
**Pull request by EU99**
### What was wrong?

Add new Chain Eurus mainnet and testnet.

### How was it fixed?

Deploy contracts and add address and initial block. 

@gnosis/safe-services

### CODE REVIEW

**Comment by EU99** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Uxio0** [comment]
Hi:
- EURUS needs to be added to https://github.com/gnosis/gnosis-py
- This PR needs to be merged first: https://github.com/gnosis/safe-deployments/pull/76

**Comment by EU99** [comment]
> Hi:
> 
> * EURUS needs to be added to https://github.com/gnosis/gnosis-py
> * This PR needs to be merged first: [Added Eurus(1008) and Eurus testnet(1984) contract addresses. safe-deployments#76](https://github.com/safe-global/safe-deployments/pull/76)

The PR has already been merged into safe-deployment.

**Comment by Uxio0** [comment]
Can you rebase `master` so tests pass?

**Review by Uxio0 — APPROVED** [review]

**Pull request merged**
