### PR TITLE
Add candle to setup_service

### PR DESCRIPTION
**Pull request by pkakelas**
### What was wrong?

Candle chain was missing

### How was it fixed?

Added candle chain deployments

### CODE REVIEW

**Review by Uxio0 — DISMISSED** [review]

**Comment by Uxio0** [comment]
Please rebase and resolve conflicts so we can merge 🙏🏻

**Comment by Uxio0** [comment]
Also https://github.com/safe-global/safe-deployments/pull/108 needs to be merged first

**Comment by samisbakedham** [comment]
> Please rebase and resolve conflicts so we can merge 🙏🏻

Will do

**Comment by samisbakedham** [comment]
> Also [safe-global/safe-deployments#108](https://github.com/safe-global/safe-deployments/pull/108) needs to be merged first

Done sir

**Comment by Uxio0** [comment]
> > Also [safe-global/safe-deployments#108](https://github.com/safe-global/safe-deployments/pull/108) needs to be merged first
> 
> Done sir

No, it's not

**Pull request closed without merging**
