### PR TITLE
Update to OpenApi3

### LINKED ISSUE #2268: Update API docs to use OAS 3
The Transaction Service's Swagger docs currently use v2 of the OpenAPI Specification, which doesn't work with some of the modern generative tools that only target OAS3. Upgrading will make the API easier to work with for local code generation (querystring filter classes, etc).

### PR DESCRIPTION
**Pull request by moisses89**
Closes #2268

### CODE REVIEW

**Review by Uxio0 — APPROVED** [review]

**Comment by Uxio0** [comment]
Approved, but for this PR the real approve will come from @JagoFigueroa checking the actual render

**Comment by moisses89** [comment]
Sharing with @JagoFigueroa for testing the openApi specification.
[Safe Transaction Service v3.txt](https://github.com/user-attachments/files/17573135/Safe.Transaction.Service.v3.txt)

to be validated with https://editor.swagger.io/ tool.

**Comment by JagoFigueroa** [comment]
Gave the swagger a couple of runs and should be looking bien rocoso after the latest changes 😄  Happy to give it a final 👀 before merging it or once merged too!

**Comment by moisses89** [comment]
> Gave the swagger a couple of runs and should be looking bien rocoso after the latest changes 😄 Happy to give it a final 👀 before merging it or once merged too!

Could you do a last review to this new schema? 
[Safe Transaction Servicev3.1.txt](https://github.com/user-attachments/files/17587059/Safe.Transaction.Servicev3.1.txt)

**Comment by JagoFigueroa** [comment]
Looking perfecto now! 🚀

**Pull request merged**
