### PR TITLE
Improve tx-processor testing

### PR DESCRIPTION
**Pull request by Uxio0**
- Wrote a new test while fixing #895

### CODE REVIEW

**Review by moisses89 — COMMENTED** [review]
There is only included the test where is the fix?

**Comment by Uxio0** [comment]
> There is only included the test where is the fix?

There's no fix. Check the name of the PR 😉

**Comment by moisses89** [comment]
> 

Agree was to confirm.

**Review by moisses89 — APPROVED** [review]
Looks good

**Pull request merged**
