### PR TITLE
add Venidium testnet safe contracts

### PR DESCRIPTION
**Pull request by itsfridaythen**
### What was wrong?

Missing safe contract addresses for Venidium Testnet network 

### How was it fixed?

Added safe contract addresses for Venidium Testnet

﻿@gnosis/safe-services

### CODE REVIEW

**Comment by Uxio0** [comment]
Please provide the PR adding this contracts to https://github.com/safe-global/safe-deployments/

**Comment by itsfridaythen** [comment]
Created a PR adding the contracts: https://github.com/safe-global/safe-deployments/pull/96

**Comment by itsfridaythen** [comment]
> Created a PR adding the contracts: [safe-global/safe-deployments#96](https://github.com/safe-global/safe-deployments/pull/96)

Merged

**Comment by Uxio0** [comment]
You still need to add the network to https://github.com/safe-global/safe-eth-py

**Comment by nicexe** [comment]
> You still need to add the network to https://github.com/safe-global/safe-eth-py

PR https://github.com/safe-global/safe-eth-py/pull/271 is already merged

**Comment by Uxio0** [comment]
> > You still need to add the network to https://github.com/safe-global/safe-eth-py
> 
> PR [safe-global/safe-eth-py#271](https://github.com/safe-global/safe-eth-py/pull/271) is already merged
> 
> Just not in a [safe-eth-py release](https://github.com/safe-global/safe-eth-py/releases) yet

Good point, I missed it. Can you update `safe-eth-py` on `requirements.txt` to `4.1.1`?

**Pull request merged**
