### PR TITLE
Remove deprecated endpoints

### PR DESCRIPTION
**Pull request by Uxio0**
- `master-copies/` -> `singletons/`
- `transactions/` -> `multisig-transactions/`

### CODE REVIEW

**Comment by Uxio0** [comment]
@hectorgomezv @iamacook @fmrsabino Could you confirm this does not affect cgw?

**Comment by iamacook** [comment]
> @hectorgomezv @iamacook @fmrsabino Could you confirm this does not affect cgw?

We have migrated to `singletons`. However, a `/transactions/` endpoint is being used [for deletion](https://github.com/safe-global/safe-client-gateway/blob/replace-imitation-data/src/datasources/transaction-api/transaction-api.service.ts#L622). Should that also be migrated (it's not marked as deprecated on Swagger)? If so, I'm assuming it has no breaking changes?

**Comment by Uxio0** [comment]
@iamacook This was not intended. I've been trying to deprecate `transactions` -> `multisig-transactions` for multiple years now, but as we use the same view when we implemented the deletion it was posible to use the old path too. You should migrate asap to `multisig-transactions`

**Comment by iamacook** [comment]
> @iamacook This was not intended. I've been trying to deprecate `transactions` -> `multisig-transactions` for multiple years now, but as we use the same view when we implemented the deletion it was posible to use the old path too. You should migrate asap to `multisig-transactions`

We weren't aware of this. I've opened a [PR migrating it](https://github.com/safe-global/safe-client-gateway/pull/1549) and will keep you informed.

**Comment by Uxio0** [comment]
> We weren't aware of this. I've opened a [PR migrating it](https://github.com/safe-global/safe-client-gateway/pull/1549) and will keep you informed.

We will then wait for the next release and don't it today

**Review by falvaradorodriguez — APPROVED** [review]

**Pull request merged**
