### PR TITLE
Add PublicMint mainNet and testNet

### PR DESCRIPTION
**Pull request by rafaeltorres-seegno**
### Make sure these boxes are checked! 📦✅

- [x] You ran `./run_tests.sh`
- [x] You ran `pre-commit run -a`
- [x] If you want to add your network to `setup_service.py`, provide a link to your
    [safe-deployments PR](https://github.com/safe-global/safe-deployments/pulls) and check network name
    exists in [safe-eth-py](https://github.com/safe-global/safe-eth-py/blob/master/gnosis/eth/ethereum_network.py)

safe-eth-py PR: https://github.com/safe-global/safe-eth-py/pull/377
safe-deployments PR: https://github.com/safe-global/safe-deployments/pull/129

### CODE REVIEW

**Comment by rafaeltorres-seegno** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by moisses89** [comment]
@rafaeltorres-seegno had you an opportunity to see this? https://github.com/safe-global/safe-deployments/pull/129#pullrequestreview-1142646676

**Comment by rafaeltorres-seegno** [comment]
@moisses89 yes, we have a PR submitted await review: [ ](https://github.com/ethereum-lists/chains/pull/1719#pullrequestreview-1143117547)
As soon as it gets approved I'll update the PRs here

**Review by Uxio0 — APPROVED** [review]

**Review by Uxio0 — CHANGES_REQUESTED** [review]
Update safe-eth-py to v4.6.0

**Comment by rafaeltorres-seegno** [comment]
@Uxio0 , @moisses89 and @hectorgomezv can we get an update on this? is there anything missing?

**Comment by Uxio0** [comment]
> @Uxio0 , @moisses89 and @hectorgomezv can we get an update on this? is there anything missing?

@rafaeltorres-seegno You must rebase `master` so tests pass, we cannot merge until tests are ok

**Comment by rafaeltorres-seegno** [comment]
@Uxio0 rebase done

**Review by Uxio0 — APPROVED** [review]

**Pull request merged**
