### PR TITLE
Don't send notifications for not trusted txs

### PR DESCRIPTION
**Pull request by Uxio0**

### CODE REVIEW

**Review by DmitryBespalov — APPROVED** [review]

**Review by moisses89 — APPROVED** [review]
Looks good to me!

**Comment by Uxio0** [comment]
@fmrsabino @hectorgomezv do you think this can have be problematic for the client gateway? I can think on the lists not being refreshed

@DmitryBespalov Mobile team must also fix this on their side

**Comment by hectorgomezv** [comment]
From my point of view, this change shouldn't be an issue on the Client Gateway side since an untrusted transaction shouldn't trigger a cache invalidation IMHO. In fact, we're explicitly sending a hardcoded `trusted=true` param for the  transaction queue retrieval in the Client Gateway new implementation 🤔

**Comment by Uxio0** [comment]
Thanks for the input @hectorgomezv , good to know

**Pull request merged**
