### PR TITLE
Add contract addresses for Meter network mainnet and testnet

### PR DESCRIPTION
**Pull request by philipappiah**
### What was wrong?
Missing contract addresses for Meter network mainnet and testnet
Closes #

### How was it fixed?
Add contract addresses for Meter network mainnet and testnet

@gnosis/safe-services

### CODE REVIEW

**Comment by philipappiah** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by philipappiah** [comment]
recheck

**Comment by Uxio0** [comment]
https://github.com/safe-global/safe-deployments/pull/86

**Review by Uxio0 — APPROVED** [review]
Looks good

**Comment by moisses89** [comment]
@Uxio0 this pull request is failing the tests because the METER_TESTNET id is not included in the EthereumNetwork enum. 
```
METER_TESTNET=83 
```

**Pull request merged**
