### PR TITLE
add rabbit chain

### PR DESCRIPTION
**Pull request by amankumarp**
### Make sure these boxes are checked! 📦✅

- [x] You ran `./run_tests.sh`
- [x] You ran `pre-commit run -a`
- [x] If you want to add your network to `setup_service.py`, provide a link to your
    [safe-deployments PR](https://github.com/safe-global/safe-deployments/pull/123) and check network name
    exists in [safe-eth-py](https://github.com/safe-global/safe-eth-py/pull/375)

### What was wrong? 👾

Closes #

### CODE REVIEW

**Comment by amankumarp** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by amankumarp** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Uxio0** [comment]
Let us know when https://github.com/safe-global/safe-deployments/pull/123 is merged

**Comment by amankumarp** [comment]
https://github.com/safe-global/safe-deployments/pull/123 is merged

**Comment by amankumarp** [comment]
please merge https://github.com/safe-global/safe-transaction-service/pull/1109 .

I will appreciate .

**Review by Uxio0 — APPROVED** [review]

**Pull request merged**
